---
- name: Prepare all nodes
  hosts: k8s_cluster
  gather_facts: yes
  roles:
    - role: common
      tags:
        - common
    - role: container-runtime
      tags:
        - container-runtime
    - role: kubernetes
      tags:
        - kubernetes

- name: Setup Kubernetes Master
  hosts: master
  gather_facts: yes
  roles:
    - role: master
      tags:
        - master
    - role: cni
      tags:
        - cni

- name: Join Worker Nodes
  hosts: workers
  gather_facts: yes
  roles:
    - role: worker
      tags:
        - worker

- name: Deploy Addons
  hosts: master
  gather_facts: yes
  roles:
    - role: addons
      tags:
        - addons
