---
- name: Ensure remote tmp directory exists
  file:
    path: /tmp/.ansible/tmp
    state: directory
    mode: '1777'

- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install HAProxy & KeepAlived
  ansible.builtin.apt:
    name:
    - haproxy
    - keepalived
    - iproute2
    - iputils-ping
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Configure sysctl parameters for HAProxy and KeepAlived
  copy:
    dest: /etc/sysctl.d/haproxy.conf
    content: |
      net.ipv4.ip_nonlocal_bind = 1
    mode: '0644'

- name: apply sysctl
  command: sysctl --system

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes

- name: Configure KeepAlived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes

- name: Enable and start HAProxy
  systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Enable and start KeepAlived
  systemd:
    name: keepalived
    state: started
    enabled: yes