---
- name: Setup HAProxy Load Balancer
  hosts: load_balancers
  gather_facts: true
  roles:
    - lb

- name: Prepare all nodes
  hosts: k8s_cluster
  gather_facts: true
  roles:
    - common
    - container-runtime
    - kubernetes
  
- name: Setup Kubernetes Master
  hosts: "{{ groups['masters'][0] }}"
  gather_facts: true
  roles:
    - master
    - cni

- name: Join Master Nodes
  hosts: masters[1:]
  gather_facts: true
  roles:
    - master-join

- name: Join Worker Nodes
  hosts: workers
  gather_facts: true
  roles:
    - worker

- name: Deploy Addons
  hosts: "{{ groups['masters'][0] }}"
  gather_facts: true
  roles:
    - addons