---
- name: Setup HAProxy Load Balancer
  hosts: load_balancers
  gather_facts: yes
  roles:
    - lb

- name: Prepare all nodes
  hosts: k8s_cluster
  gather_facts: yes
  roles:
    - common
    - container-runtime
    - kubernetes
  
- name: Setup Kubernetes Master
  hosts: masters
  gather_facts: yes
  roles:
    - master
    - cni
  when: inventory_hostname == groups['masters'][0]

- name: Join Master Nodes
  hosts: masters
  gather_facts: yes
  roles:
    - master-join
  when: inventory_hostname != groups['masters'][0]

- name: Join Worker Nodes
  hosts: workers
  gather_facts: yes
  roles:
    - worker

- name: Deploy Addons
  hosts: masters
  gather_facts: yes
  roles:
    - addons
  when: inventory_hostname == groups['masters'][0]